import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { parseCst, serializeCst } from '../../boards/cst';

const SAMPLE = `
//Copyright (C)2014-2025 Gowin Semiconductor Corporation.
//Part Number: GW2AR-LV18QN88C8/I7

IO_LOC "clk" 4;
IO_PORT "clk" IO_TYPE=LVCMOS33 PULL_MODE=UP;
IO_LOC "O_tmds_clk_p" 33,34;   // differential pair
IO_PORT "O_tmds_clk_p" IO_TYPE=LVDS25;
IO_LOC "sys_clk" H11;
`;

describe('parseCst', () => {
	it('merges IO_LOC and IO_PORT by signal and strips comments', () => {
		const { constraints, unrecognized } = parseCst(SAMPLE);
		assert.equal(unrecognized.length, 0);

		const clk = constraints.find((c) => c.signal === 'clk');
		assert.equal(clk?.loc, '4');
		assert.equal(clk?.exclusive, false);
		assert.deepEqual(clk?.attributes, { IO_TYPE: 'LVCMOS33', PULL_MODE: 'UP' });
	});

	it('keeps differential pairs and ball names verbatim (minus whitespace)', () => {
		const { constraints } = parseCst(SAMPLE);
		assert.equal(constraints.find((c) => c.signal === 'O_tmds_clk_p')?.loc, '33,34');
		assert.equal(constraints.find((c) => c.signal === 'sys_clk')?.loc, 'H11');
	});

	it('accepts spaces around the attribute "=" (SUG935 A.2)', () => {
		const { constraints } = parseCst('IO_PORT "p" IO_TYPE = LVCMOS33  DRIVE =8;');
		assert.deepEqual(constraints[0].attributes, { IO_TYPE: 'LVCMOS33', DRIVE: '8' });
	});

	it('recognises the exclusive keyword on IO_LOC', () => {
		const { constraints } = parseCst('IO_LOC "io_2" A1 exclusive;');
		assert.equal(constraints[0].loc, 'A1');
		assert.equal(constraints[0].exclusive, true);
	});

	it('collects lines it does not understand', () => {
		const { unrecognized } = parseCst('CLOCK_LOC "clk" BUFG[0] = CLK;\nIO_LOC "x" 1;');
		assert.deepEqual(unrecognized, ['CLOCK_LOC "clk" BUFG[0] = CLK;']);
	});
});

describe('serializeCst', () => {
	it('emits IO_LOC and IO_PORT with a header', () => {
		const text = serializeCst(
			[{ signal: 'led', loc: '15', attributes: { IO_TYPE: 'LVCMOS33', DRIVE: '8' } }],
			{ header: ['generated by test'] },
		);
		assert.match(text, /^\/\/ generated by test\n\n/);
		assert.match(text, /IO_LOC "led" 15;/);
		assert.match(text, /IO_PORT "led" IO_TYPE=LVCMOS33 DRIVE=8;/);
	});

	it('writes the exclusive keyword back out', () => {
		const text = serializeCst([{ signal: 'io', loc: 'A1', exclusive: true, attributes: {} }]);
		assert.match(text, /IO_LOC "io" A1 exclusive;/);
	});

	it('round-trips a parsed file', () => {
		const once = parseCst(`${SAMPLE}\nIO_LOC "io_x" B2 exclusive;`);
		const twice = parseCst(serializeCst(once.constraints));
		assert.deepEqual(twice.constraints, once.constraints);
	});
});
