/**
 * Read the top module's ports (name, direction, width) with yosys, so the
 * port → pin mapping can be offered for any HDL the user brings.
 *
 * yosys only parses and elaborates here (`hierarchy` + `proc` on the top
 * module); no synthesis, so it takes well under a second even for a CPU.
 * Gowin primitives (OSER10, TLVDS_OBUF, …) are read as black boxes from
 * yosys's own cell library so designs that instantiate them elaborate.
 *
 * The planning and JSON parsing are pure; the run is injected like the
 * build stages, so all of it is unit-tested without a real yosys.
 */

import * as path from 'node:path';
import type { PortDirection } from '../boards/schema';
import { buildLayout } from '../build/layout';
import type { ProcessRunner } from '../build/runStep';
import { readSourceCommands } from '../build/yosys';
import type { FpgaProject } from './schema';

export interface TopPort {
	readonly name: string;
	readonly dir: PortDirection;
	readonly width: number;
	/** Index of the first bit (yosys `offset`), e.g. 0 for `[7:0]`. */
	readonly offset: number;
}

export interface PortQueryPlan {
	readonly scriptPath: string;
	readonly scriptText: string;
	readonly jsonPath: string;
	readonly args: readonly string[];
}

export type PortQueryPlanResult =
	| { readonly ok: true; readonly plan: PortQueryPlan }
	| { readonly ok: false; readonly errors: readonly string[] };

export function planPortQuery(project: FpgaProject, projectRoot: string): PortQueryPlanResult {
	const { readLines, errors } = readSourceCommands(project);
	if (errors.length > 0) {
		return { ok: false, errors };
	}
	const layout = buildLayout(projectRoot);
	const scriptPath = path.join(layout.netlistDir, 'ports.ys');
	const jsonPath = path.join(layout.netlistDir, 'ports.json');
	const rel = (p: string): string => path.relative(projectRoot, p).split(path.sep).join('/');

	const scriptText = [
		'# ports.ys — generated by OpenFPGA Deck to list the top module\'s ports.',
		'read_verilog -lib -specify +/gowin/cells_sim.v',
		...readLines,
		`hierarchy -top ${project.top}`,
		`select ${project.top}`,
		'proc',
		`write_json -selected -noscopeinfo ${rel(jsonPath)}`,
		'',
	].join('\n');

	return { ok: true, plan: { scriptPath, scriptText, jsonPath, args: ['-q', '-s', rel(scriptPath)] } };
}

/** Ports of `top` from yosys `write_json` output, in declaration order. */
export function parsePorts(jsonText: string, top: string): TopPort[] {
	const json = JSON.parse(jsonText) as {
		modules?: Record<string, { ports?: Record<string, Record<string, unknown>> }>;
	};
	const ports = json.modules?.[top]?.ports;
	if (!ports) {
		throw new Error(`yosys output has no module "${top}".`);
	}
	return Object.entries(ports).map(([name, p]) => ({
		name,
		dir: p.direction as PortDirection,
		width: Array.isArray(p.bits) ? p.bits.length : 1,
		offset: typeof p.offset === 'number' ? p.offset : 0,
	}));
}

/** `.cst` signal names for each bit of a port: `clk`, or `led[0]` … `led[5]`. */
export function portBitNames(port: TopPort): string[] {
	if (port.width === 1 && port.offset === 0) {
		return [port.name];
	}
	return Array.from({ length: port.width }, (_, i) => `${port.name}[${port.offset + i}]`);
}

export interface PortQueryIo {
	readonly run: ProcessRunner;
	readonly mkdirp: (dir: string) => Promise<void>;
	readonly writeFile: (file: string, text: string) => Promise<void>;
	readonly readFile: (file: string) => Promise<string>;
}

export type PortQueryResult =
	| { readonly ok: true; readonly ports: TopPort[] }
	| { readonly ok: false; readonly error: string };

export async function readTopPorts(
	project: FpgaProject,
	projectRoot: string,
	yosysExe: string,
	io: PortQueryIo,
): Promise<PortQueryResult> {
	const planned = planPortQuery(project, projectRoot);
	if (!planned.ok) {
		return { ok: false, error: planned.errors.join(' ') };
	}
	const { plan } = planned;
	await io.mkdirp(path.dirname(plan.scriptPath));
	await io.writeFile(plan.scriptPath, plan.scriptText);

	let output = '';
	const result = await io.run({
		exe: yosysExe,
		args: plan.args,
		cwd: projectRoot,
		onChunk: (text) => {
			output += text;
		},
	});
	if (result.spawnError) {
		return { ok: false, error: `Could not start yosys: ${result.spawnError}` };
	}
	if (result.code !== 0) {
		const error = output.split(/\r?\n/).find((l) => l.startsWith('ERROR:'));
		return { ok: false, error: error ?? `yosys exited with code ${result.code}.` };
	}
	try {
		return { ok: true, ports: parsePorts(await io.readFile(plan.jsonPath), project.top) };
	} catch (err) {
		return { ok: false, error: `Could not read the ports yosys wrote: ${String(err)}` };
	}
}
