/**
 * Turn the Project Settings panel's create-mode answers into the files a new
 * OpenFPGA Deck project needs.
 * Pure — no filesystem, no VS Code — so it is straightforward to unit-test.
 */

import { serializeCst, type CstConstraint } from '../boards/cst';
import { pinAttributes, type Board } from '../boards/schema';
import type { TopPort } from './ports';

export type HdlLanguage = 'systemverilog' | 'verilog';
export type StarterDesign = 'blink' | 'empty';

export interface ScaffoldRequest {
	readonly name: string;
	readonly top: string;
	readonly language: HdlLanguage;
	readonly design: StarterDesign;
	readonly board: Board;
}

export interface ScaffoldFile {
	/** Path relative to the project root, POSIX separators. */
	readonly path: string;
	readonly content: string;
}

export interface ScaffoldPlan {
	readonly dirs: readonly string[];
	readonly files: readonly ScaffoldFile[];
}

const MODULE_NAME_RE = /^[A-Za-z_][A-Za-z0-9_$]*$/;
const PROJECT_NAME_RE = /^[A-Za-z0-9][A-Za-z0-9_-]*$/;

export function validateProjectName(value: string): string | undefined {
	return PROJECT_NAME_RE.test(value.trim())
		? undefined
		: 'Use letters, digits, "-" and "_"; start with a letter or digit.';
}

/** Verilog / SystemVerilog keywords that cannot be used as names. */
const HDL_KEYWORDS = new Set(
	(
		'always always_comb always_ff always_latch and assign automatic begin bit buf byte case casex casez ' +
		'class const default defparam disable do else end endcase endfunction endgenerate endmodule endtask ' +
		'enum for force forever fork function generate genvar if initial inout input int integer interface ' +
		'localparam logic longint module nand negedge nor not or output package parameter posedge reg ' +
		'repeat return shortint signed struct supply0 supply1 task time tri typedef union unsigned wait ' +
		'while wire wor xnor xor'
	).split(' '),
);

export function validateModuleName(value: string): string | undefined {
	const name = value.trim();
	if (!MODULE_NAME_RE.test(name)) {
		return 'Must be a valid HDL identifier.';
	}
	return HDL_KEYWORDS.has(name) ? `"${name}" is a Verilog keyword.` : undefined;
}

/** Board signals that look like LEDs (`led`, `led[0]`, …), ordered numerically. */
function ledSignals(board: Board): string[] {
	return Object.keys(board.pins)
		.filter((signal) => /^led(\[\d+\])?$/i.test(signal))
		.sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
}

/** True when the board has enough pins for the blink starter design. */
export function canBlink(board: Board): boolean {
	return board.pins.clk !== undefined && ledSignals(board).length > 0;
}

/** Board signals the blink starter uses: the clock and every LED. */
export function blinkSignals(board: Board): string[] {
	return ['clk', ...ledSignals(board)];
}

export function planScaffold(req: ScaffoldRequest): ScaffoldPlan {
	const ext = req.language === 'verilog' ? 'v' : 'sv';
	const hdlPath = `src/${req.top}.${ext}`;
	const cstPath = `constraints/${req.top}.cst`;

	const blink = req.design === 'blink' && canBlink(req.board);
	const signals = blink ? blinkSignals(req.board) : ['clk'];

	return {
		dirs: ['src', 'constraints', 'build'],
		files: [
			{ path: 'fpga.yaml', content: projectYaml(req.name, req.board.id, req.top, [hdlPath], cstPath) },
			{ path: hdlPath, content: hdl(req, blink) },
			{ path: cstPath, content: cst(req, signals) },
			{ path: '.gitignore', content: '/build/\n' },
		],
	};
}

/** A new project's `fpga.yaml`. */
export function projectYaml(
	name: string,
	boardId: string,
	top: string,
	sources: readonly string[],
	cstPath: string,
): string {
	return [
		'# fpga.yaml — OpenFPGA Deck project',
		`name: ${name}`,
		`board: ${boardId}`,
		`top: ${top}`,
		'',
		'sources:',
		...sources.map((s) => `  - ${s}`),
		'',
		'constraints:',
		`  - ${cstPath}`,
		'',
	].join('\n');
}

function cst(req: ScaffoldRequest, signals: readonly string[]): string {
	const constraints: CstConstraint[] = [];
	for (const signal of signals) {
		const pin = req.board.pins[signal];
		if (pin) {
			constraints.push({ signal, loc: pin.loc, attributes: pinAttributes(req.board, signal) });
		}
	}
	return serializeCst(constraints, {
		header: [
			`${req.name} — physical constraints for ${req.board.name}`,
			'Generated by OpenFPGA Deck.',
		],
	});
}

function hdl(req: ScaffoldRequest, blink: boolean): string {
	if (!blink) {
		return topModuleSource(req, [{ name: 'clk', dir: 'input', width: 1, offset: 0 }]);
	}
	const width = ledSignals(req.board).length;
	const bit = blinkBit(req.board);
	return req.language === 'verilog'
		? blinkVerilog(req, width, bit)
		: blinkSystemVerilog(req, width, bit);
}

/** Counter bit that toggles at roughly 1 Hz for the board's main clock. */
function blinkBit(board: Board): number {
	const hz = (board.clocks[0]?.mhz ?? 27) * 1_000_000;
	return Math.max(1, Math.round(Math.log2(hz)) - 1);
}

function blinkSystemVerilog(req: ScaffoldRequest, width: number, bit: number): string {
	return `// ${req.name} — blink the on-board LEDs.
// Generated by OpenFPGA Deck. The Tang Nano 20K LEDs are active-low.

module ${req.top} (
    input  logic clk,
    output logic [${width - 1}:0] led
);

    logic [${bit}:0] counter = '0;

    always_ff @(posedge clk) begin
        counter <= counter + 1'b1;
    end

    assign led = {${width}{~counter[${bit}]}};

endmodule
`;
}

function blinkVerilog(req: ScaffoldRequest, width: number, bit: number): string {
	return `// ${req.name} — blink the on-board LEDs.
// Generated by OpenFPGA Deck. The Tang Nano 20K LEDs are active-low.

module ${req.top} (
    input  clk,
    output [${width - 1}:0] led
);

    reg [${bit}:0] counter = ${bit + 1}'d0;

    always @(posedge clk)
        counter <= counter + 1'b1;

    assign led = {${width}{~counter[${bit}]}};

endmodule
`;
}

export interface TopModuleRequest {
	readonly name: string;
	readonly top: string;
	readonly language: HdlLanguage;
}

/** An empty top module with the given ports (e.g. from {@link portsFromBoardSignals}). */
export function topModuleSource(req: TopModuleRequest, ports: readonly TopPort[]): string {
	const sv = req.language === 'systemverilog';
	const decls = ports.map((p, i) => {
		const kind = sv ? (p.dir === 'inout' ? ' wire' : ' logic') : '';
		const range = p.width > 1 ? ` [${p.offset + p.width - 1}:${p.offset}]` : '';
		const sep = i < ports.length - 1 ? ',' : '';
		return `    ${p.dir.padEnd(6)}${kind}${range} ${p.name}${sep}`;
	});
	return `// ${req.name} — top module. Generated by OpenFPGA Deck.

module ${req.top} (
${decls.join('\n')}
);

    // Add your logic here.

endmodule
`;
}
