/**
 * Turn a few wizard answers into the files a new OpenFPGA Deck project needs.
 * Pure — no filesystem, no VS Code — so it is straightforward to unit-test.
 */

import { serializeCst, type CstConstraint } from '../boards/cst';
import { pinAttributes, type Board } from '../boards/schema';

export type HdlLanguage = 'systemverilog' | 'verilog';
export type StarterDesign = 'blink' | 'empty';

export interface ScaffoldRequest {
	readonly name: string;
	readonly top: string;
	readonly language: HdlLanguage;
	readonly design: StarterDesign;
	readonly board: Board;
}

export interface ScaffoldFile {
	/** Path relative to the project root, POSIX separators. */
	readonly path: string;
	readonly content: string;
}

export interface ScaffoldPlan {
	readonly dirs: readonly string[];
	readonly files: readonly ScaffoldFile[];
}

const MODULE_NAME_RE = /^[A-Za-z_][A-Za-z0-9_$]*$/;
const PROJECT_NAME_RE = /^[A-Za-z0-9][A-Za-z0-9_-]*$/;

export function validateProjectName(value: string): string | undefined {
	return PROJECT_NAME_RE.test(value.trim())
		? undefined
		: 'Use letters, digits, "-" and "_"; start with a letter or digit.';
}

export function validateModuleName(value: string): string | undefined {
	return MODULE_NAME_RE.test(value.trim()) ? undefined : 'Must be a valid HDL identifier.';
}

/** Board signals that look like LEDs (`led`, `led[0]`, …), ordered numerically. */
function ledSignals(board: Board): string[] {
	return Object.keys(board.pins)
		.filter((signal) => /^led(\[\d+\])?$/i.test(signal))
		.sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
}

/** True when the board has enough pins for the blink starter design. */
export function canBlink(board: Board): boolean {
	return board.pins.clk !== undefined && ledSignals(board).length > 0;
}

export function planScaffold(req: ScaffoldRequest): ScaffoldPlan {
	const ext = req.language === 'verilog' ? 'v' : 'sv';
	const hdlPath = `src/${req.top}.${ext}`;
	const cstPath = `constraints/${req.top}.cst`;

	const blink = req.design === 'blink' && canBlink(req.board);
	const signals = blink ? ['clk', ...ledSignals(req.board)] : ['clk'];

	return {
		dirs: ['src', 'constraints', 'build'],
		files: [
			{ path: 'fpga.yaml', content: fpgaYaml(req, hdlPath, cstPath) },
			{ path: hdlPath, content: hdl(req, blink) },
			{ path: cstPath, content: cst(req, signals) },
			{ path: '.gitignore', content: '/build/\n' },
		],
	};
}

function fpgaYaml(req: ScaffoldRequest, hdlPath: string, cstPath: string): string {
	return [
		'# fpga.yaml — OpenFPGA Deck project',
		`name: ${req.name}`,
		`board: ${req.board.id}`,
		`top: ${req.top}`,
		'',
		'sources:',
		`  - ${hdlPath}`,
		'',
		'constraints:',
		`  - ${cstPath}`,
		'',
	].join('\n');
}

function cst(req: ScaffoldRequest, signals: readonly string[]): string {
	const constraints: CstConstraint[] = [];
	for (const signal of signals) {
		const pin = req.board.pins[signal];
		if (pin) {
			constraints.push({ signal, loc: pin.loc, attributes: pinAttributes(req.board, signal) });
		}
	}
	return serializeCst(constraints, {
		header: [
			`${req.name} — physical constraints for ${req.board.name}`,
			'Generated by OpenFPGA Deck.',
		],
	});
}

function hdl(req: ScaffoldRequest, blink: boolean): string {
	if (!blink) {
		return req.language === 'verilog' ? emptyVerilog(req) : emptySystemVerilog(req);
	}
	const width = ledSignals(req.board).length;
	const bit = blinkBit(req.board);
	return req.language === 'verilog'
		? blinkVerilog(req, width, bit)
		: blinkSystemVerilog(req, width, bit);
}

/** Counter bit that toggles at roughly 1 Hz for the board's main clock. */
function blinkBit(board: Board): number {
	const hz = (board.clocks[0]?.mhz ?? 27) * 1_000_000;
	return Math.max(1, Math.round(Math.log2(hz)) - 1);
}

function blinkSystemVerilog(req: ScaffoldRequest, width: number, bit: number): string {
	return `// ${req.name} — blink the on-board LEDs.
// Generated by OpenFPGA Deck. The Tang Nano 20K LEDs are active-low.

module ${req.top} (
    input  logic clk,
    output logic [${width - 1}:0] led
);

    logic [${bit}:0] counter = '0;

    always_ff @(posedge clk) begin
        counter <= counter + 1'b1;
    end

    assign led = {${width}{~counter[${bit}]}};

endmodule
`;
}

function blinkVerilog(req: ScaffoldRequest, width: number, bit: number): string {
	return `// ${req.name} — blink the on-board LEDs.
// Generated by OpenFPGA Deck. The Tang Nano 20K LEDs are active-low.

module ${req.top} (
    input  clk,
    output [${width - 1}:0] led
);

    reg [${bit}:0] counter = ${bit + 1}'d0;

    always @(posedge clk)
        counter <= counter + 1'b1;

    assign led = {${width}{~counter[${bit}]}};

endmodule
`;
}

function emptySystemVerilog(req: ScaffoldRequest): string {
	return `// ${req.name} — top module. Generated by OpenFPGA Deck.

module ${req.top} (
    input logic clk
);

    // Add your logic here.

endmodule
`;
}

function emptyVerilog(req: ScaffoldRequest): string {
	return `// ${req.name} — top module. Generated by OpenFPGA Deck.

module ${req.top} (
    input clk
);

    // Add your logic here.

endmodule
`;
}
