// blink — blink the on-board LEDs.
// Generated by OpenFPGA Deck. The Tang Nano 20K LEDs are active-low.

module top (
    input  clk,
    output [5:0] led
);

    reg [24:0] counter = 25'd0;

    always @(posedge clk)
        counter <= counter + 1'b1;

    assign led = {6{~counter[24]}};

endmodule
